name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.0.2'
        architecture: x64
      env:
        KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        AUTOCD_DOMAIN_BASE: .kloud.software
        CI_REGISTRY: registry.kloudfile.io
        CI_REGISTRY_USER:  kloudsoftware
        CI_REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
        K8S_SECRET_NEEDED: false
        K8S_STORAGE_CLASS: nfs-client
    - name: Run docker
      run: |
        docker run hello-world
        java -version
        curl --version
        git --version
