name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.0.2'
        architecture: x64
      env:
        KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}  
    - name: Run docker
      run: |
        docker run hello-world
        java -version
